### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by hkhesehus** [hkhesehus/jira-time#22]
Proposals:

- ALT+ARROW UP/DOWN: Navigate up/down in work log comment/time/date
- ALT+SHIFT+ARROW UP/DOWN: Move work log up/down in task list

- CTRL+S: Trigger sync
- CTRL+F: Quick filter (requires #21 to be implemented first)
- CTRL+A: Quick add issue (requires #17 to be implemented first)
- CTRL+T: Add new tab (requires #15 to be implemented first)
- CTRL+W: Close current tab (requires #15 to be implemented first)

**Comment by SquashMan** [comment]
CTRL+S has been implemented.
If someone wants to add more, feature/JT-22-keyboard-shortcuts is the current active branch for this development.

**Comment by hkhesehus** [comment]
Implemented filter issues and 'tab' for moving between record comments. Closing since we might not have tabs at all.
