### ISSUE TITLE
OOP coding style?

### ISSUE THREAD

**Issue by Kukks** [hkhesehus/jira-time#25]
Would incorporating the OOP paradigm be beneficial to the project using something like [react-redux-oop](https://github.com/newtoncodes/react-redux-oop)?

**Comment by hkhesehus** [comment]
Perhaps, if we see that this tool can grow in size an complexity. Not sure if it will. It can however serve as a nice playground for how to implement OOP :)

**Comment by hkhesehus** [comment]
React and redux does not really invite to OOP. Closing the issue, but everyone should keep doing OOP for utility classes where this makes sense
