### ISSUE TITLE
Faulty record time display

### ISSUE THREAD

**Issue by apacicaps** [hkhesehus/jira-time#9]
When you stop a log after for example 1 hour and 25 minutes, the time on the record line says 1 hour. It syncs correctly to Jira, but it would be nice to be able to see the exact time span in Jira Time.

**Comment by hkhesehus** [comment]
We are currently using the [Elapsed](https://www.npmjs.com/package/elapsed) package to display the time:

`elapsedTime: new Elapsed(record.startTime, record.endTime || Date.now()).optimal`

There might be other options than "optimal" we can use to display it better

**Comment by hkhesehus** [comment]
It is up for grabs :)
